version: "3.4"

services:   
  postgres:
    image: postgres
    container_name: go-blog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    container_name: go-blog-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9090:9090"
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres

  frontend:
    build: ./frontend
    container_name: go-blog-frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend