version: 1.0.0

services:   
  postgres:
    image: postgres
    container_name: go-blog_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "6969:6969"
  sqlite:
    image: dockerpinata/sqlite
    container_name: go-blog_sqlite
    volumes:
      - ./sqlite:/db
    ports:
      - "1448:1448"